config/routes.rb
CheckPrice::Application.routes.draw do
  get "digitalitems/index"
  root 'digitalitems#index'
  resources :digitalitems do
    collection {get "check"}
  end

end

app/models/digital_item.rb
class DigitalItem < ActiveRecord::Base
    def self.check(date)
        rel = where("itemid LIKE ?", "#{date}%")  
    end
end

app/models/price.rb
class Price
  # MixIn
  include ActiveModel::Model
  #require 'nokogiri'
  
  def self.check
    
    prev_url = "https://store.ishibashi.co.jp/ec/proList/doSearch/srDispProductList/1/1/%20/11430000000/1/%20/%20/%20/%20/%20/%20/1/40/"
    post_url = "/0?jp=on&wd=%20&searchType=0&excludeSearchWord=&facetSearchType=0"
    item_array = Array.new
    price_array = Array.new
    item_num = 0  
    
    url = prev_url + item_num.to_s + post_url
    require 'open-uri'
    doc = Nokogiri::HTML(open(url))
    
    doc.xpath("//p[@class=\"item\"]").each do |item|
      item_array.push(item.text.gsub("\/ ","").gsub(" …",""))
    end
   
    item_array
  
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/digitalitems_controller.rb
class DigitalitemsController < ApplicationController
  #before_action :set_item, only: [:show]

  def index
    #@digitalitems=DigitalItem.all
    #️@item = DigitalItem.new()
    #@items = DigitalItem.select(:itemid)
  end
  
  def show
    @item=DigitalItem.find(params[:id]) 
  end
  
  def check
      @digitalitems=DigitalItem.paginate(page: params[:page], per_page: 40).check(params[:q])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @item = DigitalItem.new()
    @items = DigitalItem.select(:itemid)
  end
  
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Check Price"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/digitalitems_helper.rb
module DigitalitemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/digitalitems/check.html.erb
<%= will_paginate %>

<table class="table">
  <thead>
    <tr><span class="index">
      <th>ItemID</th>
    </span></tr>  
  </thead>
  <% @digitalitems.each do |item| %>
  <tbody>
    <tr><span class="index">
      <td><%= item.itemid %> 
          <%= link_to 'Show', digitalitem_path(item) %> 
          <%= link_to 'Index', digitalitems_path %>
      </td>
    </span></tr>
  </tbody>
  <% end %>
</table>

<%= will_paginate %>

app/views/digitalitems/index.html.erb
<%= form_tag(:check_digitalitems, method: "get") do %>

  <%= select_tag(:q, options_for_select([['2018年09月23日', 20180923], ['2018年09月28日', 20180928]])) %>
  <%= submit_tag("Check") %>

<% end %>

app/views/digitalitems/show.html.erb
<tr><span class="index">
  <td><%= @item.itemid %></td>
  <td><%= @item.name %></td>
  <td><%= @item.price %></td>
  <td><%= link_to 'Index', digitalitems_path %></td>
</span></tr>

app/views/home/index.html.erb
<%= form_for(@item) do |f| %>
  <%= f.collection_select :itemid, @items, :itemid, :itemid %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Check Price", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",    digitalitems_path %></li>
            <li><%= link_to "Help",    '#' %></li>
            <li><%= link_to "Sign in", '#' %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>